version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki:/etc/loki:ro
      - loki_data:/data/loki
    user: "10001:10001"
    depends_on:
      - loki-init

  loki-init:
    image: busybox
    command: sh -c "mkdir -p /data/loki/chunks /data/loki/index /data/loki/boltdb-cache /data/loki/compactor /data/loki/wal /data/loki/rules && chown -R 10001:10001 /data/loki"
    volumes:
      - loki_data:/data/loki
    user: root

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./monitoring/promtail:/etc/promtail
      - app_logs:/var/log/vertx
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki

volumes:
  loki_data:
  app_logs:
