version: '3.8'

services:
  loki:
    image: grafana/loki:2.8.4
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./logs:/var/log/vertx
      - ./monitoring/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
