version: '3.8'

services:
  api-gateway:
    image:  ghcr.io/kiquetal/vertx-gateway-apis:amd64-20251029
    pull_policy: always
    volumes:
      - app_logs:/app/logs

    ports:
      - "8080:8080"  # Application port
    environment:
      - LOG_LEVEL=INFO
      - LOG_LEVEL_APP=DEBUG
      - LOG_PATH=/app/logs
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
    name: external_gateway_network

volumes:
  prometheus_data:
  grafana_data:
  app_logs:
    driver: local
    name: external_app_logs_volume
