services:
  loki:
    image: grafana/loki:2.9.0
    command:
    - "-config.file=/etc/loki/loki-config.yml"
    ports:
      - "3100:3100"
      - "9095:9095"  # Adding gRPC port
    volumes:
      - ./monitoring/loki:/etc/loki:ro
      - loki_data:/data/loki
    user: "10001:10001"
    depends_on:
      - loki-init
    networks:
    - external_gateway_network

  loki-init:
    image: busybox
    command: sh -c "mkdir -p /data/loki/chunks /data/loki/index /data/loki/boltdb-cache /data/loki/compactor /data/loki/wal /data/loki/rules && chown -R 10001:10001 /data/loki"
    volumes:
      - loki_data:/data/loki
    user: root

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
    volumes:
      # Mount your local config file as read-only
      # I've assumed it's in a local './alloy' directory
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy:ro

      # --- This is the key improvement ---
      # Persist the data directory using a named volume
      - alloy_data:/var/lib/alloy/data

      - external_app_logs_volume:/var/log/vertx:ro
    # Use the list format for the command, just like we fixed
    # for Loki and the agent in our previous conversation.
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
    depends_on:
      - loki
    # You will also need to add your agent to the network
    # so it can see Loki
    networks:
      - external_gateway_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
    networks:
    - external_gateway_network


volumes:
  loki_data:
  alloy_data:
  external_app_logs_volume:
    external: true
networks:
  external_gateway_network:
    external: true
