server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: vertx-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: vertx
          app: gateway
          __path__: /var/log/vertx/application*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            thread: thread
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000"
      - labels:
          level:
          logger:
          thread:
