server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: vertx-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: vertx
          app: gateway
          __path__: /var/log/vertx/application*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            thread: thread
