### Test Dynamic GRPC Greeter Service
POST http://localhost:8080/api/greeter/sayHello
Content-Type: application/json

{
    "namex": "Volveran las oscuras golondrinas!!!!"
}

### Test with different input
POST http://localhost:8080/api/greeter/sayHello
Content-Type: application/json

{
    "name": "Vertx Gateway"
}

### Expected responses will be:
# First request:
# {
#   "message": "Hello World"
# }
#
# Second request:
# {
#   "message": "Hello Vertx Gateway"
# }
