### Test the dynamic gRPC endpoint
POST http://localhost:8080/api/greeter/sayHello
Content-Type: application/json

{
  "name": "World"
}

### Expected response will be:
# {
#   "message": "Hello World"
# }
