global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vertx-application'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          application: 'vertx-gateway'
          type: 'application'

  - job_name: 'vertx-jmx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8081']
        labels:
          application: 'vertx-gateway'
          type: 'jmx'
